### PR TITLE
add docker dev files for local development

### PR DESCRIPTION
**Pull request by gempir**
Trying to make it easier to contribute. 

But I think I fucked up the rustlog container because it does not compile. Don't really understand the error though.

```
56.65    Compiling async-compression v0.4.1
56.94    Compiling tower-http v0.4.3
57.50    Compiling axum-prometheus v0.3.4
57.92    Compiling rustlog v0.1.0 (/app)
58.65 error: future cannot be sent between threads safely
58.65    --> src/migrator/mod.rs:105:47
58.65     |
58.65 105 |                       let handle = tokio::spawn(async move {
58.65     |  _______________________________________________^
58.65 106 | |                         let mut inserter = migrator
58.65 107 | |                             .db
58.65 108 | |                             .inserter(MESSAGES_TABLE)?
58.65 ...   |
58.65 155 | |                         Result::<_, anyhow::Error>::Ok(())
58.65 156 | |                     });
58.65     | |_____________________^ future created by async block is not `Send`
58.65     |
58.65     = help: within `[async block@src/migrator/mod.rs:105:47: 156:22]`, the trait `std::marker::Send` is not implemented for `*mut (twitch::Tag<'static>, &'static str)`
58.65 note: future is not `Send` as this value is used across an await
58.65    --> src/migrator/mod.rs:270:37
58.65     |
58.65 248 |         Ok(irc_message) => {
58.65     |            ----------- has type `twitch::Message` which is not `Send`
58.65 ...
58.65 270 |             inserter.write(&message).await?;
58.65     |                                     ^^^^^^ await occurs here, with `irc_message` maybe used later
58.65 271 |         }
58.65     |         - `irc_message` is later dropped here
58.65 note: required by a bound in `tokio::spawn`
58.65    --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/task/spawn.rs:166:21
58.65     |
58.65 166 |         T: Future + Send + 'static,
58.65     |                     ^^^^ required by this bound in `spawn`
58.65
58.68 error[E0599]: the method `par_iter` exists for reference `&[Message]`, but its trait bounds were not satisfied
58.68   --> src/logs/mod.rs:26:10
58.68    |
58.68 25 | /     irc_messages
58.68 26 | |         .par_iter()
58.68    | |_________-^^^^^^^^
58.68    |
58.68    = note: the following trait bounds were not satisfied:
58.68            `&[twitch::Message]: IntoParallelIterator`
58.68            which is required by `[twitch::Message]: IntoParallelRefIterator<'_>`
58.68            `&&[twitch::Message]: IntoParallelIterator`
58.68            which is required by `&[twitch::Message]: IntoParallelRefIterator<'_>`
58.68
58.77 error[E0277]: `*mut (twitch::Tag<'static>, &'static str)` cannot be sent between threads safely
58.77    --> src/logs/mod.rs:12:10
58.77     |
58.77 12  |         .filter_map(|raw| match twitch::Message::parse(raw) {
58.77     |          ^^^^^^^^^^ `*mut (twitch::Tag<'static>, &'static str)` cannot be sent between threads safely
58.77     |
58.77     = help: within `twitch::Message`, the trait `std::marker::Send` is not implemented for `*mut (twitch::Tag<'static>, &'static str)`
58.77     = note: required because it appears within the type `ParsedTags<'static>`
58.77     = note: required because it appears within the type `Option<ParsedTags<'static>>`
58.77     = note: required because it appears within the type `Message`
58.77 note: required by a bound in `rayon::iter::ParallelIterator::filter_map`
58.77    --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.7.0/src/iter/mod.rs:833:12
58.77     |
58.77 833 |         R: Send,
58.77     |            ^^^^ required by this bound in `ParallelIterator::filter_map`
58.77
58.78 error[E0599]: `rayon::iter::FilterMap<rayon::vec::IntoIter<std::string::String>, [closure@src/logs/mod.rs:12:21: 12:26]>` is not an iterator
58.78   --> src/logs/mod.rs:19:10
58.78    |
58.78 10 | /     lines
58.78 11 | |         .into_par_iter()
58.78 12 | |         .filter_map(|raw| match twitch::Message::parse(raw) {
58.78 13 | |             Ok(msg) => Some(msg),
58.78 ...  |
58.78 18 | |         })
58.78 19 | |         .collect()
58.78    | |         -^^^^^^^ `rayon::iter::FilterMap<rayon::vec::IntoIter<std::string::String>, [closure@src/logs/mod.rs:12:21: 12:26]>` is not an iterator
58.78    | |_________|
58.78    |
58.78    |
58.78   ::: /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.7.0/src/iter/filter_map.rs:13:1
58.78    |
58.78 13 |   pub struct FilterMap<I: ParallelIterator, P> {
58.78    |   -------------------------------------------- doesn't satisfy `_: Iterator`
58.78    |
58.78    = note: the following trait bounds were not satisfied:
58.78            `rayon::iter::FilterMap<rayon::vec::IntoIter<std::string::String>, [closure@src/logs/mod.rs:12:21: 12:26]>: Iterator`
58.78            which is required by `&mut rayon::iter::FilterMap<rayon::vec::IntoIter<std::string::String>, [closure@src/logs/mod.rs:12:21: 12:26]>: Iterator`
58.78
58.83 warning: unused import: `IntoParallelRefIterator`
58.83  --> src/logs/mod.rs:6:44
58.83   |
58.83 6 | use rayon::prelude::{IntoParallelIterator, IntoParallelRefIterator, ParallelIterator};
58.83   |                                            ^^^^^^^^^^^^^^^^^^^^^^^
58.83   |
58.83   = note: `#[warn(unused_imports)]` on by default
58.83
58.84 Some errors have detailed explanations: E0277, E0599.
58.84 For more information about an error, try `rustc --explain E0277`.
58.85 warning: `rustlog` (bin "rustlog") generated 1 warning
58.85 error: could not compile `rustlog` (bin "rustlog") due to 4 previous errors; 1 warning emitted
58.88 error: failed to compile `rustlog v0.1.0 (/app)`, intermediate artifacts can be found at `/app/target`
------
failed to solve: process "/bin/sh -c cargo install --path /app" did not complete successfully: exit code: 101
```

Any hints?

### CODE REVIEW

**Comment by boring-nick** [comment]
Hi, sorry for taking a long time to respond.

Regarding the compile error: this is caused by `cargo install` (unfortunately) not using the lockfile by default, and instead pulling the latest versions of dependencies. This is fixed by using the `--locked` option.

As for the PR overall: I really like the idea of making it easier to contribute, but I have some questions.
How do you want the workflow to look when using the dev containers? Change code>rebuild image>start container>test? Or should it be a persistent container which recompiles the program automatically on code changes?

In the first case, IMO it would make sense to also build the frontend, at which point you might as well use the main Dockerfile for this purpose, as it also has caching configured to avoid recompiling all the dependencies every time.

In the second case, there would either need to be 2 containers, or a single container running 2 processes for recompiling rust (via `cargo-watch` for example) as well as the frontend with `yarn start`. This would let you test your changes faster, but is more complex.

Personally, I'm not a fan of doing this kind of development in Docker using either approach, as it creates an extra layer of friction between the program and the development environment (not using system compiler settings, can't attach a debugger easily, also it creates noticeable overhead on non-Linux systems due to running in a VM) and rustlog doesn't have many system dependencies that you need to install. Though I definitely agree that simplifying the database setup would be nice.

Would you be fine with having a ready-to-go docker-compose in the repo for setting up the database, and running rustlog itself with `cargo run` on the host? If yes, then that's the option that I would like to have. if not, then please tell me which of the "fully dockerized" approaches you would prefer.

**Comment by gempir** [comment]
Yeah, I agree, it's probably not wise to run the backend in a container in the dev environment. Equally with the frontend.

I think for ease-of-use it should just use a Makefile or some similar one shot command tool. 

`make watch-backend` (also runs docker-compose up on the db)  and `make watch-frontend` or something like that.

**Comment by boring-nick** [comment]
@gempir I've added a guide and some setup files in #16 . Unfortunately making it a one-shot watch command would require several external tools installed, and that is something I would like to avoid. However there are step-by-step instructions on how to get it running, hopefully those will be helpful enough. Please take a look at the PR and tell me if it's clear enough for a first time contributor (it's kinda hard for me to judge this)

**Comment by gempir** [comment]
I think that's great! Thank you!

**Pull request closed without merging**
